package models

import "time"

// OrdersNew 结构体定义 orders_new 表的结构
type OrdersNew struct {
	ID                        int        `gorm:"primaryKey"`
	OrderID                   string     `gorm:"column:order_id"`
	ZMOrderNo                 string     `gorm:"column:zm_order_no"`
	OutRequestNo              string     `gorm:"column:out_request_no"`
	ZMUserID                  string     `gorm:"column:zm_user_id"`
	UserName                  string     `gorm:"column:user_name"`
	UserPhone                 string     `gorm:"column:user_phone"`
	UserIDNumber              string     `gorm:"column:user_id_number"`
	ReceiverName              string     `gorm:"column:receiver_name"`
	ReceiverPhone             string     `gorm:"column:receiver_phone"`
	UserEmail                 string     `gorm:"column:user_email"`
	UserAddress               string     `gorm:"column:user_address"`
	OrderStatus               int        `gorm:"column:order_status"`
	MerID                     int        `gorm:"column:mer_id"`
	GoodsID                   int        `gorm:"column:goods_id"`
	AttrID                    string     `gorm:"column:attr_id"`
	CateID                    int        `gorm:"column:cate_id"`
	GoodsName                 string     `gorm:"column:goods_name"`
	GoodsOrderAttr            string     `gorm:"column:goods_order_attr"`
	GoodsOrderThumbnail       string     `gorm:"column:goods_order_thumbnail"`
	GoodsOfficialPrice        float64    `gorm:"column:goods_official_price"`
	OrderMonthlyRent          float64    `gorm:"column:order_monthly_rent"`
	OrderGrossRent            float64    `gorm:"column:order_gross_rent"`
	OrderDayRent              string     `gorm:"column:order_day_rent"`
	OrderTenancyTerm          int        `gorm:"column:order_tenancy_term"`
	OrderRepayPeriod          int        `gorm:"column:order_repay_period"`
	OrderRemaAmountPay        float64    `gorm:"column:order_rema_amount_pay"`
	OrderAmountActuallyPaid   float64    `gorm:"column:order_amount_actually_paid"`
	BuyMoney                  float64    `gorm:"column:buy_money"`
	OrderAmountOverride       float64    `gorm:"column:order_amount_override"`
	OrderGrossCreditRent      float64    `gorm:"column:order_gross_credit_rent"`
	ZMCreditAmount            float64    `gorm:"column:zm_credit_amount"`
	SafeID                    string     `gorm:"column:safe_id"`
	OrderGoodsInsurance       float64    `gorm:"column:order_goods_insurance"`
	ElectronicContractNumber  string     `gorm:"column:electronic_contract_number"`
	NotaryID                  string     `gorm:"column:notary_id"`
	Express                   string     `gorm:"column:express"`
	ExpNumber                 string     `gorm:"column:exp_number"`
	ExpressData               string     `gorm:"column:express_data"`
	ExpressImg                string     `gorm:"column:express_img"`
	AdminUserID               int        `gorm:"column:admin_user_id"`
	GoodsLeaseWayID           int        `gorm:"column:goods_lease_way_id"`
	IsDelete                  int        `gorm:"column:is_delete"`
	ReturnStatus              int        `gorm:"column:return_status"`
	OrderDownPaymentType      int        `gorm:"column:order_down_payment_type"`
	NotaryImg                 string     `gorm:"column:notary_img"`
	CancelStatus              int        `gorm:"column:cancel_status"`
	IsKeepRent                int        `gorm:"column:is_keep_rent"`
	CancelTime                *time.Time `gorm:"column:cancel_time"`
	RelationOrder             string     `gorm:"column:relationOrder"`
	InsuranceCoverage         float64    `gorm:"column:insuranceCoverage"`
	PolicyNo                  string     `gorm:"column:PolicyNo"`
	PolicyUrl                 string     `gorm:"column:PolicyUrl"`
	InsuranceAmount           float64    `gorm:"column:insurance_amount"`
	OverdueDay                int        `gorm:"column:overdue_day"`
	OrderRemarks              string     `gorm:"column:order_remarks"`
	Note                      string     `gorm:"column:note"`
	ExperienceRentalIsRelet   int        `gorm:"column:experience_rental_is_relet"`
	ExperienceRentalDay       int        `gorm:"column:experience_rental_day"`
	ExperienceRentalStartTime *time.Time `gorm:"column:experience_rental_start_time"`
	ExperienceRentalEndTime   *time.Time `gorm:"column:experience_rental_end_time"`
	AssignOrderTime           *time.Time `gorm:"column:assign_order_time"`
	IsFirstMonthOneYuan       int        `gorm:"column:is_first_month_one_yuan"`
	OrderEnsureAmount         float64    `gorm:"column:order_ensure_amount"`
	OrderFinishTime           *time.Time `gorm:"column:order_finish_time"`
	OrderBuyoutTime           *time.Time `gorm:"column:order_buyout_time"`
	MaterialID                string     `gorm:"column:material_id"`
	OrderTab                  int        `gorm:"column:order_tab"`
	SerialNumber              string     `gorm:"column:serial_number"`
	OrderCreateTime           time.Time  `gorm:"column:order_create_time"`
	OrderDeliveryTime         time.Time  `gorm:"column:order_delivery_time"`
	OrderLeaseStartTime       *time.Time `gorm:"column:order_lease_start_time"`
	OrderReceivTime           time.Time  `gorm:"column:order_receiv_time"`
	OrderLastOverdue          time.Time  `gorm:"column:order_last_overdue"`
	IsPolicy                  int        `gorm:"column:is_policy"`
	Platform                  string     `gorm:"column:platform"`
	ThirdUserID               string     `gorm:"column:third_user_id"`
	NotaryImgOne              string     `gorm:"column:notary_img_one"`
	NotaryImgTwo              string     `gorm:"column:notary_img_two"`
	OrderPayTime              *time.Time `gorm:"column:order_pay_time"`
	OutOrderNo                string     `gorm:"column:out_order_no"`
	UserVoucherID             int        `gorm:"column:user_voucher_id"`
	OrderAuditPassTime        *time.Time `gorm:"column:order_audit_pass_time"`
}
